### ISSUE TITLE
Option to disable ROS dependency?

### ISSUE THREAD

**Issue by traversaro** [isri-aist/QpSolverCollection#1]
Hello @mmurooka, and thanks a lot for your work in this repo, it is quite useful!

I was wondering if you would be open to PR that introduced a CMake option by default off, to permit to compile the library without roscpp and catkin? The option could be call something like `QP_SOLVER_COLLECTION_STANDALONE` or `QP_SOLVER_COLLECTION_WITHOUT_ROS`. This would be quite helpful in contexts where a ROS dependency is not desirable, for example because ROS is not available or use of the library in ROS2. If you are ok with this, I would be happy to provide such a PR.

Thanks again in any case.

**Comment by mmurooka** [comment]
Hello @traversaro, the proposed changes are welcome!

**Comment by mmurooka** [comment]
Close as https://github.com/isri-aist/QpSolverCollection/pull/5 is merged
