### ISSUE TITLE
JRL_QP cmake option makes build error...?

### ISSUE THREAD

**Issue by TsuruMasato** [isri-aist/QpSolverCollection#17]
Hello, this is Tsuru.

I am trying to use JRL-QP, especially for [differentiable_rmap](https://github.com/isri-aist/differentiable_rmap),
and caught an error when I run catkin build.

Originally, I have been using QLD solver only with `-DENABLE_QLD=ON` for a long time.
Today, I wanted to try Murooka-sensei's reachability map, so that I enabled " JRL-QP" flag in catkin conf and I met this error.

I can see `qp_solver_collection` tried to find `eigen-lssolConfig`.
I thought it may be coming from benchmark comparison, then I tried with `-DBUILD_TESTING=OFF -DBUILD_BENCHMARKS=OFF` options. Even though, it didn't work...

Does anyone know why it always goes to find `eigen lssol`?

I will start to look into the codes from this noon by myself, but please let me rise this issue at the beginning.

Thank you in advance.

![Screenshot from 2023-01-26 11-40-18](https://user-images.githubusercontent.com/14979823/214746729-627d8545-9240-46cd-bae2-460d4571cddd.png)

```
Errors     << qp_solver_collection:check /home/masato/src/catkin_motion6DoF_ws/logs/qp_solver_collection/build.check.1152.log                                                                              
- ENABLE_QLD: ON
- ENABLE_QUADPROG: OFF
- ENABLE_LSSOL: OFF
CMake Error at /usr/share/cmake-3.25/Modules/CMakeFindDependencyMacro.cmake:47 (find_package):
  By not providing "Findeigen-lssol.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "eigen-lssol", but CMake did not find one.

  Could not find a package configuration file provided by "eigen-lssol" with
  any of the following names:

    eigen-lssolConfig.cmake
    eigen-lssol-config.cmake

  Add the installation prefix of "eigen-lssol" to CMAKE_PREFIX_PATH or set
  "eigen-lssol_DIR" to a directory containing one of the above files.  If
  "eigen-lssol" provides a separate development package or SDK, be sure it
  has been installed.
Call Stack (most recent call first):
  /home/masato/openrtp/lib/cmake/jrl-qp/jrl-qpConfig.cmake:109 (find_dependency)
  CMakeLists.txt:34 (find_package)
  CMakeLists.txt:50 (add_qp_solver)


make: *** [cmake_check_build_system] Error 1
cd /home/masato/src/catkin_motion6DoF_ws/build/qp_solver_collection; catkin build --get-env qp_solver_collection | catkin env -si  /usr/bin/make cmake_check_build_system; cd -
```

**Comment by mmurooka** [comment]
Do you install the latest master branch of jrl-qp?

**Comment by mmurooka** [comment]
Also, your qp_solver_collection seems to be old version, so I recommend updating it to the latest version.

**Comment by TsuruMasato** [comment]
Sorry, my bad.
My JRL_QP had an old cmake cache with benchmark option.
After clean build, it worked perfectly!!

https://user-images.githubusercontent.com/14979823/214775046-f7550886-0511-4825-901f-27fe5ef9cc92.mp4
